service: audio-clipper-slackbot

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  memorySize: 128
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          method: post
          path: /slack/events
