org: edoror
app: audio-clipper
service: audio-clipper-slackbot
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  memorySize: 512
  timeout: 30
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          method: post
          path: /slack/events
          response:
            headers:
              Content-Type: "'text/html'"
    layers:
      - {Ref: FfmpegLambdaLayer}

layers:
  ffmpeg:
    path: layer
