resources:
  - name: audio-clipper
    type: git
    source:
      uri: https://github.com/medoror/audio_clipper_slackbot.git
      branch: master
      username: ((github.username))
      password: ((github.password))

  - name: deploy-app
    type: cf
    source:
      api: ((cf.api))
      username: ((cf.username))
      password: ((cf.password))
      organization: ((cf.org))
      space: ((cf.space))
      skip_cert_check: true

jobs:
  - name: run-ci-tests
    public: true
    plan:
      - get: audio-clipper
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
             repository: node
             tag: "8.12-alpine"
          inputs:
            - name: audio-clipper
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                cd audio-clipper
                npm install
                npm test
  - name: deploy
    public: true
    serial: true
    plan:
      - get: audio-clipper
        passed: [run-ci-tests]
        trigger: true
      - task: build-app
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
             repository: node
             tag: "8.12-alpine"
          inputs:
            - name: audio-clipper
          outputs:
            - name: artifacts
          run:
            path: /bin/sh
            args:
              - -c
              - |
                export SLACK_SIGNING_SECRET=((slack.secret))
                export SLACK_BOT_TOKEN=((slack.token))
                cd audio-clipper
                npm install
                ./node_modules/typescript/bin/tsc
                cd ..
                cp -r audio-clipper/* artifacts/
      - put: deploy-app
        params:
          manifest: audio-clipper/manifest.yml
          path: artifacts
