image-config: &image-config
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: node
      tag: "8.12-alpine"

resources:
  - name: audio-clipper
    type: git
    source:
      uri: https://github.com/medoror/audio_clipper_slackbot.git
      branch: master
      username: ((github.username))
      password: ((github.password))

  - name: deploy-app
    type: cf
    source:
      api: ((cf.api))
      username: ((cf.username))
      password: ((cf.password))
      organization: ((cf.org))
      space: ((cf.space))
      skip_cert_check: true

  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))


jobs:
  - name: run-ci-tests
    public: true
    plan:
      - get: audio-clipper
        trigger: true
      - task: run-tests
        config:
          <<: *image-config
          inputs:
            - name: audio-clipper
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                cd audio-clipper
                npm install
                npm test

  - name: deploy-to-cf
    public: true
    serial: true
    plan:
      - get: audio-clipper
        passed: [run-ci-tests]
        trigger: true
      - task: build-app
        config:
          <<: *image-config
          inputs:
            - name: audio-clipper
          outputs:
            - name: audio-clipper-compiled
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd audio-clipper
                npm install
                npm build
                cd ..
                cp -r audio-clipper/* audio-clipper-compiled/

      - put: deploy-app
        params:
          manifest: audio-clipper/manifest.yml
          path: audio-clipper-compiled
