resources:
  - name: audio-clipper
    type: git
    source:
      uri: https://github.com/medoror/audio_clipper_slackbot.git
      branch: master
      username: ((github-username))
      password: ((github-password))

  - name: node-docker-image
    type: docker-image
    source:
      repository: node
      tag: "8.12-alpine"

  - name: deply-app
    type: cf
    source:
      api: ((cf-api-url))
      username: ((cf-api-email))
      password: ((cf-api-password))
      organization: ((cf-api-org))
      space: ((cf-api-space))
      skip_cert_check: true

jobs:
  - name: run-ci-tests
    public: true
    plan:
      - get: audio-clipper
        trigger: true
      - get: node-docker-image
      - task: run-testsr
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                cd audio-clipper-slackbot
                npm install
                npm test
  - name: deploy
    plan:
      - get: audio-clipper
        passed: [run-ci-tests]
      - get: deply-app
      - task: deploy
      - put: deply-app
        params:
          manifest: audio-clipper/manifest.yml